/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nasaafundPlatformSol from "./NasaafundPlatform.sol";
export type { nasaafundPlatformSol };
export type { NasaafundNFT } from "./NasaafundNFT";
export type { Nasaafunding } from "./Nasaafunding";
